(function(){
var hero=document.getElementById('hero');
var gm=document.getElementById('gm'),st=document.getElementById('st'),tb=document.getElementById('tb'),cur=null,keyf=null,tmr=0,raf=0,pending=[],cleanup=null;
(function(){var c=document.createElement('canvas');c.width=c.height=16;var x=c.getContext('2d'),i,j,v;for(i=0;i<16;i++)for(j=0;j<16;j++){v=38+((i*7+j*13+((i*j)%5)*9)%23);x.fillStyle='rgb('+v+','+(v+2)+','+(v+7)+')';x.fillRect(i,j,1,1)}gm.style.setProperty('--tex','url('+c.toDataURL()+')')})();
function later(fn,ms){var id=setTimeout(function(){pending=pending.filter(function(x){return x!==id});if(gm.classList.contains("on"))fn()},ms);pending.push(id);return id}
function stop(){stopParty();if(cleanup)cleanup();clearInterval(tmr);cancelAnimationFrame(raf);pending.forEach(clearTimeout);pending=[];keyf=null}
function el(t,c,h){var e=document.createElement(t);if(c)e.className=c;if(h!=null)e.innerHTML=h;return e}
function swipe(e,f){var x,y;e.addEventListener('touchstart',function(t){x=t.touches[0].clientX;y=t.touches[0].clientY},{passive:true});
e.addEventListener('touchend',function(t){var dx=t.changedTouches[0].clientX-x,dy=t.changedTouches[0].clientY-y;if(Math.max(Math.abs(dx),Math.abs(dy))<20)return;f(Math.abs(dx)>Math.abs(dy)?(dx>0?'R':'L'):(dy>0?'D':'U'))},{passive:true})}
function art(kind){var shapes={
crystal:'<path d="M24 4 42 20 24 44 6 20Z" fill="#55c5bd" stroke="#b2f6da" stroke-width="2"/><path d="m24 4-7 16 7 24 8-24Z" fill="#89e2d1"/><path d="M6 20h36" stroke="#285f77"/>',
cube:'<path d="m24 5 18 10v22L24 47 6 37V15Z" fill="#b08b59"/><path d="m24 5 18 10-18 10L6 15Z" fill="#80bc6e"/><path d="M24 25v22L6 37V15Z" fill="#705e46"/><path d="m8 17 16 9 16-9v7l-16 9-16-9Z" fill="#4a8d51"/>',
moon:'<path d="M34 6A20 20 0 1 0 42 33 17 17 0 0 1 34 6Z" fill="#d9d5ff"/><path d="m37 12 2 5 5 1-5 2-2 5-1-5-5-2 5-1Z" fill="#c2a4ff"/>',
leaf:'<path d="M40 6C8 4 1 33 15 39 31 44 43 28 40 6Z" fill="#70b880" stroke="#b9e39d" stroke-width="2"/><path d="m8 45 28-28M18 35l-2-11m9 4 11-1" stroke="#31584b" stroke-width="3"/>',
flame:'<path d="M24 3c5 15 14 15 13 28-1 15-27 18-27 0 0-8 6-11 8-20 0 9 4 12 6 12 4-8 1-14 0-20Z" fill="#efa36a"/><path d="M25 23c10 11 4 22-3 20-8-2-6-9 3-20Z" fill="#fff0a0"/>',
sword:'<path d="m31 5 11-2-2 11L20 33 14 27Z" fill="#bde5ed" stroke="#4f8db0" stroke-width="2"/><path d="m12 24 12 12-4 4L8 28Z" fill="#e9bb6a"/><path d="m13 32 6 6-9 9-6-6Z" fill="#866244"/>',
creeper:'<path d="M6 7h36v31H6Z" fill="#80bd74" stroke="#bdd694" stroke-width="2"/><path d="M6 10h8v9H6m26 10h10v7H32M15 7h9v5h-9" fill="#5f9368"/><path d="M12 17h8v8h-8m16-8h8v8h-8M20 25h8v5h5v10h-7v-5h-4v5h-7V30h5Z" fill="#173234"/><path d="M10 41h28v5H10Z" fill="#467959"/>',
flag:'<path d="M13 5v39" stroke="#bddae2" stroke-width="3"/><path d="m15 6 25 4-10 8 10 8-25-3Z" fill="#e89baf"/><path d="M8 44h14" stroke="#bddae2" stroke-width="3"/>',
bomb:'<circle cx="24" cy="29" r="16" fill="#506477" stroke="#bdd3df" stroke-width="2"/><path d="m24 13 2-5 8 1 3-5" fill="none" stroke="#e3b778" stroke-width="3"/><path d="m35 3 3 3m-2 3 5-1" stroke="#ffa868" stroke-width="2"/><circle cx="18" cy="24" r="4" fill="#93aabc"/>',
rock:'<path d="m7 20 8-12 17-3 11 15-5 20-26 3-8-13Z" fill="#8294ac" stroke="#c9d9e7" stroke-width="2"/><path d="m15 8 10 15 18-3-18 14-13 9 3-23-11 10" fill="none" stroke="#4b5b73" stroke-width="2"/>',
paper:'<path d="M11 5h24l6 8v30H11Z" fill="#e4dbc4" stroke="#fff3d5" stroke-width="2"/><path d="M35 5v9h6M17 21h18M17 28h18M17 35h12" fill="none" stroke="#a19986" stroke-width="2"/>',
scissors:'<circle cx="12" cy="36" r="7" fill="none" stroke="#bd92db" stroke-width="4"/><circle cx="35" cy="36" r="7" fill="none" stroke="#bd92db" stroke-width="4"/><path d="m16 30 21-26-9 22-13 6M31 31 9 4l10 21 13 7" fill="#cee3ea"/><circle cx="24" cy="24" r="3" fill="#62768d"/>'};return '<svg class="articon" viewBox="0 0 48 48" aria-hidden="true">'+(shapes[kind]||shapes.crystal)+'</svg>'}
var rounds=Array(10).fill(1),currentGame=-1,vibrationOn=true,lastBuzz=0,roundLabel=null;try{vibrationOn=localStorage.getItem('arcade-vibration')!=='off'}catch(e){}function buzz(type){if(!vibrationOn||document.hidden||!navigator.vibrate)return;var now=performance.now();if(type==='tap'&&now-lastBuzz<70)return;if(type==='hit'&&now-lastBuzz<45)return;lastBuzz=now;try{navigator.vibrate(type==='win'?[22,30,35]:type==='over'?[35,35,45]:type==='hit'?20:8)}catch(e){}}function showRound(){if(roundLabel)roundLabel.textContent='Round '+rounds[currentGame]}function nextRound(){if(currentGame>=0){rounds[currentGame]++;showRound()}}function roundReset(fn){var first=true;return function(){if(first)first=false;else nextRound();return fn.apply(this,arguments)}}
gm.addEventListener('pointerdown',function(e){if(e.target.closest('button,canvas,.tfjoy,.tfaim'))buzz('tap')},{passive:true});
var cheerAudio=null,cheerSound=true,partyFrame=0,partyCanvas=null,cheerNodes=[];try{cheerSound=localStorage.getItem('arcade-cheer-sound')!=='off'}catch(e){}function unlockCheer(){if(!cheerSound)return;try{var Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;if(!cheerAudio)cheerAudio=new Audio();if(cheerAudio.state==='suspended')cheerAudio.resume().catch(function(){})}catch(e){}}gm.addEventListener('pointerdown',unlockCheer,{passive:true});gm.addEventListener('keydown',unlockCheer);function stopParty(){cancelAnimationFrame(partyFrame);if(partyCanvas)partyCanvas.remove();partyCanvas=null;cheerNodes.forEach(function(node){try{node.stop()}catch(e){}});cheerNodes=[]}function victory(){if(!gm.classList.contains('on')||document.hidden)return;stopParty();buzz('win');var parent=document.fullscreenElement||gm,rect=parent.getBoundingClientRect(),canvas=document.createElement('canvas');canvas.className='winparty';canvas.setAttribute('aria-hidden','true');canvas.width=Math.min(800,Math.ceil(rect.width));canvas.height=Math.min(800,Math.ceil(rect.height));parent.appendChild(canvas);partyCanvas=canvas;var ctx=canvas.getContext('2d'),W=canvas.width,H=canvas.height,start=performance.now(),last=start,pieces=[],palette=['#ff7ca8','#ffd77b','#91dfbd','#8ecaf4','#c3a0ff'];for(var i=0;i<(window.roshanLowPower?10:36);i++){var side=i%2;pieces.push({x:side?W:0,y:H*.5,vx:(side?-1:1)*(80+Math.random()*150),vy:-180-Math.random()*190,angle:Math.random()*6,spin:Math.random()*5-2.5,color:palette[i%palette.length]})}var reduced=window.matchMedia&&matchMedia('(prefers-reduced-motion: reduce)').matches;function draw(now){if(partyCanvas!==canvas)return;var t=(now-start)/1000,dt=Math.min(.04,(now-last)/1000);last=now;if(t>1.65||document.hidden){canvas.remove();partyCanvas=null;return}ctx.clearRect(0,0,W,H);ctx.globalAlpha=Math.min(1,(1.65-t)*2);if(!reduced)pieces.forEach(function(p){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=420*dt;p.angle+=p.spin*dt;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.angle);ctx.fillStyle=p.color;ctx.fillRect(-3,-5,6,10);ctx.restore()});ctx.fillStyle='#102032ed';ctx.beginPath();ctx.roundRect(W/2-107,H*.34-27,214,58,14);ctx.fill();ctx.fillStyle='#fff0b5';ctx.font='bold 20px monospace';ctx.textAlign='center';ctx.fillText('WOOHOO! YEAH!',W/2,H*.34+9);partyFrame=requestAnimationFrame(draw)}partyFrame=requestAnimationFrame(draw);
if(cheerSound){unlockCheer();if(cheerAudio&&cheerAudio.state==='running'){var now=cheerAudio.currentTime;[523.25,659.25,783.99,1046.5].forEach(function(freq,i){var osc=cheerAudio.createOscillator(),gain=cheerAudio.createGain();osc.type='triangle';osc.frequency.setValueAtTime(freq,now+i*.12);osc.frequency.exponentialRampToValueAtTime(freq*1.06,now+i*.12+.12);gain.gain.setValueAtTime(0,now+i*.12);gain.gain.linearRampToValueAtTime(.1,now+i*.12+.018);gain.gain.exponentialRampToValueAtTime(.001,now+i*.12+.22);osc.connect(gain);gain.connect(cheerAudio.destination);osc.start(now+i*.12);osc.stop(now+i*.12+.23);cheerNodes.push(osc)})}}}
var games=[
['Snake',function(){var cv=el('canvas','g');cv.width=300;cv.height=300;var c=cv.getContext('2d'),sc=el('div','sc'),s,d,nd,f,sco,dead;
function reset(){s=[[7,7],[6,7],[5,7]];d=nd='R';sco=0;dead=0;food()}function food(){do{f=[Math.random()*15|0,Math.random()*15|0]}while(s.some(function(p){return p[0]==f[0]&&p[1]==f[1]}))}
function dir(k){var o={L:'R',R:'L',U:'D',D:'U'};if(o[k]!=d)nd=k}
function draw(){c.fillStyle='#11272b';c.fillRect(0,0,300,300);for(var yy=0;yy<15;yy++)for(var xx=0;xx<15;xx++){c.fillStyle=(xx+yy)%2?'#183431':'#1c3934';c.fillRect(xx*20+1,yy*20+1,18,18)}c.fillStyle='#e9a19e';c.beginPath();c.arc(f[0]*20+10,f[1]*20+11,6,0,Math.PI*2);c.fill();c.fillStyle='#fff1c7';c.fillRect(f[0]*20+7,f[1]*20+7,3,3);c.fillStyle='#7eb790';c.fillRect(f[0]*20+10,f[1]*20+3,4,3);s.forEach(function(p,i){var x=p[0]*20,y=p[1]*20;c.fillStyle=i?'#74b68b':'#d5e9a2';c.beginPath();c.roundRect(x+2,y+2,16,16,5);c.fill();c.fillStyle=i?'#9acba0':'#f2f4c7';c.fillRect(x+5,y+3,8,3);if(!i){c.fillStyle='#203b39';if(d==='L'||d==='R'){var ox=d==='R'?13:5;c.fillRect(x+ox,y+5,2,3);c.fillRect(x+ox,y+12,2,3)}else{var oy=d==='D'?13:5;c.fillRect(x+5,y+oy,3,2);c.fillRect(x+12,y+oy,3,2)}}});sc.innerHTML='GARDEN SNAKE · '+sco+(dead?' · Game over':'')+'<button>Restart</button>';sc.querySelector('button').onclick=function(){reset();draw()}}
function tick(){if(document.hidden||dead)return;d=nd;var h=s[0].slice();if(d=='L')h[0]--;if(d=='R')h[0]++;if(d=='U')h[1]--;if(d=='D')h[1]++;
if(h[0]<0||h[1]<0||h[0]>14||h[1]>14||s.some(function(p){return p[0]==h[0]&&p[1]==h[1]})){dead=1;buzz('over')}else{s.unshift(h);if(h[0]==f[0]&&h[1]==f[1]){sco++;saveBest('Snake',sco);buzz('win');food()}else s.pop()}draw()}
reset=roundReset(reset);reset();draw();var snakeLast=0,snakeElapsed=0;function snakeLoop(now){if(!document.hidden){snakeElapsed+=Math.min(80,now-snakeLast||0);if(snakeElapsed>=270){snakeElapsed-=270;tick()}}snakeLast=now;raf=requestAnimationFrame(snakeLoop)}raf=requestAnimationFrame(snakeLoop);keyf=function(k){dir({ArrowLeft:'L',ArrowRight:'R',ArrowUp:'U',ArrowDown:'D'}[k])};swipe(cv,dir);
var dp=el('div','dp');[['','U',''],['L','D','R']].forEach(function(r){r.forEach(function(k){var b=el('button','',k?{L:'&#9664;',R:'&#9654;',U:'&#9650;',D:'&#9660;'}[k]:'');if(!k)b.style.visibility='hidden';b.onclick=function(){dir(k)};dp.appendChild(b)})});
st.append(sc,cv,dp,el('div','sc','Swipe on the board or use the buttons'))}],
['Tic-Tac-Toe',function(){var board=Array(9).fill(''),two=true,turn='X',finished=false,matchOver=false,round=1,completed=0,points={X:0,O:0},draws=0,limit=3,names={X:'Player 1',O:'Player 2'},result='',modes=el('div','ttmodes'),panel=el('div','ttsetup'),scores=el('div','ttscore'),sc=el('div','ttstatus'),g=el('div','bd t3'),actions=el('div','ttactions'),hint=el('div','sc','Same phone · X and O take turns · Win = 1 point · Draw = 0 points');var labels={},inputs={},modeButtons=[];
['X','O'].forEach(function(k,i){var label=el('label','',i?'Player 2 · O':'Player 1 · X'),input=document.createElement('input');input.type='text';input.maxLength=20;input.placeholder=i?'Player 2 name':'Player 1 name';input.value=names[k];input.autocomplete='off';input.setAttribute('aria-label',i?'Player 2 name':'Player 1 name');input.oninput=function(){names[k]=input.value.trim()||(k==='X'?'Player 1':'Player 2');update()};label.appendChild(input);panel.appendChild(label);inputs[k]=input});var roundPick=document.createElement('select'),roundField=el('label','','Rounds');[3,5,7,0].forEach(function(n){var option=document.createElement('option');option.value=n;option.textContent=n?n+' rounds':'Unlimited';roundPick.appendChild(option)});roundPick.setAttribute('aria-label','Number of rounds');roundPick.onchange=function(){limit=+roundPick.value;newMatch()};roundField.appendChild(roundPick);panel.appendChild(roundField);
function player(k){return !two&&k==='O'?'Computer':names[k]}function sync(){rounds[1]=round;showRound();if(roundLabel)roundLabel.textContent='Round '+round+(limit?' / '+limit:'')}
function newMatch(){clearLine();board.fill('');points={X:0,O:0};draws=0;round=1;completed=0;finished=false;matchOver=false;turn='X';result='';sync();update()}
['2 players','Vs computer'].forEach(function(text,i){var button=el('button','',text);button.onclick=function(){two=i===0;newMatch()};modes.appendChild(button);modeButtons.push(button)});
var winIdx=null,lineSvg=null;function winLine(b){for(var i=0;i<wins.length;i++){var r=wins[i];if(b[r[0]]&&b[r[0]]===b[r[1]]&&b[r[0]]===b[r[2]])return r}return null}
function clearLine(){winIdx=null;if(lineSvg){lineSvg.remove();lineSvg=null}}
function showLine(r,k){clearLine();var a=cells[r[0]],b=cells[r[2]],ax=a.offsetLeft+a.offsetWidth/2,ay=a.offsetTop+a.offsetHeight/2,bx=b.offsetLeft+b.offsetWidth/2,by=b.offsetTop+b.offsetHeight/2,dx=bx-ax,dy=by-ay,len=Math.sqrt(dx*dx+dy*dy)||1,ext=a.offsetWidth*.34,ux=dx/len*ext,uy=dy/len*ext,col=k==='X'?'#ff5d4f':'#4fe3ff',ns='http:'+'//www.w3.'+'org/2000/svg';var svg=document.createElementNS(ns,'svg');svg.setAttribute('class','wline');svg.setAttribute('width',g.clientWidth);svg.setAttribute('height',g.clientHeight);[[col,a.offsetWidth*.3,.28],[col,a.offsetWidth*.13,.9],['#fff',a.offsetWidth*.05,1]].forEach(function(p){var l=document.createElementNS(ns,'line');l.setAttribute('x1',ax-ux);l.setAttribute('y1',ay-uy);l.setAttribute('x2',bx+ux);l.setAttribute('y2',by+uy);l.setAttribute('pathLength',1);l.setAttribute('stroke',p[0]);l.setAttribute('stroke-width',p[1]);l.setAttribute('stroke-opacity',p[2]);l.setAttribute('stroke-linecap','round');svg.appendChild(l)});g.appendChild(svg);lineSvg=svg;winIdx=r}
var wins=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];function winner(b){for(var i=0;i<wins.length;i++){var r=wins[i];if(b[r[0]]&&b[r[0]]===b[r[1]]&&b[r[0]]===b[r[2]])return b[r[0]]}return b.every(Boolean)?'D':''}
function minimax(b,p){var w=winner(b);if(w)return w==='O'?1:w==='X'?-1:0;var best=p==='O'?-2:2;for(var i=0;i<9;i++)if(!b[i]){b[i]=p;var v=minimax(b,p==='O'?'X':'O');b[i]='';best=p==='O'?Math.max(best,v):Math.min(best,v)}return best}
function ai(){var best=-2,index=-1;for(var i=0;i<9;i++)if(!board[i]){board[i]='O';var value=minimax(board,'X');board[i]='';if(value>best){best=value;index=i}}if(index>=0)board[index]='O'}
var cells=[];for(var i=0;i<9;i++){(function(i){var cell=el('button','','');cell.type='button';cell.setAttribute('aria-label','Cell '+(i+1));cell.onclick=function(){if(board[i]||finished)return;board[i]=turn;if(!two&&!winner(board))ai();var w=winner(board);if(w){finished=true;completed++;if(w==='D'){draws++;result='Draw - no points this round.';buzz('hit')}else{showLine(winLine(board),w);points[w]++;result=player(w)+' wins Round '+round+'! +1 point';if(two||w==='X')victory();else buzz('over')}matchOver=!!limit&&completed>=limit;if(!matchOver)round++;sync()}else if(two)turn=turn==='X'?'O':'X';update()};g.appendChild(cell);cells.push(cell)})(i)}
var statusText=document.createElement('span');sc.appendChild(statusText);var next=el('button','','Next round'),restart=el('button','','New match');next.onclick=function(){if(!finished||matchOver)return;clearLine();board.fill('');finished=false;turn=round%2?'X':'O';if(!two)turn='X';result='';update()};restart.onclick=newMatch;actions.append(next,restart);
function update(){sync();modeButtons[0].setAttribute('aria-pressed',two);modeButtons[1].setAttribute('aria-pressed',!two);inputs.O.disabled=!two;cells.forEach(function(cell,i){if(cell.textContent!==board[i])cell.textContent=board[i];cell.style.color=board[i]==='X'?'#ff5d4f':'#4fe3ff';cell.disabled=!!board[i]||finished});scores.replaceChildren();['X','O'].forEach(function(k){var card=el('div','ttpoint'),name=el('span','',null),number=el('b','',points[k]),mark=el('small','',k+' · points');name.textContent=player(k);card.append(name,number,mark);scores.appendChild(card)});var summary=el('small','ttsummary',completed+' finished · '+draws+' draw'+(draws===1?'':'s'));scores.appendChild(summary);if(matchOver){var win=points.X===points.O?'Match drawn':player(points.X>points.O?'X':'O')+' wins the match';statusText.textContent=result+' '+win+'!'}else statusText.textContent=finished?result+' Round '+round+' is ready.':player(turn)+' ('+turn+') - your turn';next.hidden=!finished||matchOver;next.textContent='Start Round '+round;hint.textContent=(two?'Same phone · Take turns':'Play against the computer')+' · Win = 1 point · Draw = 0 points'}
st.append(modes,panel,scores,sc,g,actions,hint);newMatch()}],
['Memory',function(){var E=['sword','cube','crystal','moon','leaf','flame'].map(art),a=E.concat(E).sort(function(){return Math.random()-.5}),op=[],mt=0,mv=0,lock=0,sc=el('div','sc'),g=el('div','bd mm');
function draw(){g.innerHTML='';a.forEach(function(v,i){var shown=op.indexOf(i)>-1||a[i]==null;var b=el('button',shown?'up':'',shown?(v==null?'':v):'✦');if(v==null){b.style.opacity=.25;b.style.visibility='hidden'}b.onclick=function(){if(lock||op.indexOf(i)>-1||a[i]==null)return;op.push(i);draw();if(op.length==2){mv++;lock=1;later(function(){if(a[op[0]]==a[op[1]]){a[op[0]]=a[op[1]]=null;mt++;if(mt===6)victory();else buzz('win')}op=[];lock=0;draw()},650)}};g.appendChild(b)});
sc.innerHTML='Moves '+mv+(mt==6?' - You won!':'')+'<button>Restart</button>';sc.querySelector('button').onclick=function(){nextRound();cur()}}
draw();st.append(sc,g)}],
['2048',function(){var won2048=false;var n=4,gr,sco,sc=el('div','sc'),bx=el('div','g2'),col={0:'#35373d',2:'#b9d6dc',4:'#96c5c7',8:'#88bdb1',16:'#82bfa0',32:'#b1ba86',64:'#d5b87e',128:'#dda16e',256:'#d88785',512:'#c480b8',1024:'#ab86ce',2048:'#edce91'};
function add(){var e=[];gr.forEach(function(r,y){r.forEach(function(v,x){if(!v)e.push([y,x])})});if(e.length){var p=e[Math.random()*e.length|0];gr[p[0]][p[1]]=Math.random()<.9?2:4}}
function reset(){won2048=false;gr=[[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]];sco=0;add();add();draw()}
function line(r){var a=r.filter(Boolean),o=[];for(var i=0;i<a.length;i++){if(a[i]==a[i+1]){o.push(a[i]*2);sco+=a[i]*2;i++}else o.push(a[i])}while(o.length<4)o.push(0);return o}
function mv(k){var old=JSON.stringify(gr),t;
if(k=='L')gr=gr.map(line);if(k=='R')gr=gr.map(function(r){return line(r.slice().reverse()).reverse()});
if(k=='U'||k=='D'){t=[0,1,2,3].map(function(x){var c=gr.map(function(r){return r[x]});return k=='U'?line(c):line(c.slice().reverse()).reverse()});gr=[0,1,2,3].map(function(y){return t.map(function(c){return c[y]})})}
if(JSON.stringify(gr)!=old){add();buzz('hit');if(!won2048&&gr.some(function(row){return row.some(function(v){return v>=2048})})){won2048=true;victory()}}draw()}
var cells=[],boardSize=0;for(var cell=0;cell<16;cell++){var node=el('div','c','');bx.appendChild(node);cells.push(node)}function draw(){var w=bx.clientWidth||320,cs=(w-16-18)/4;if(w!==boardSize){boardSize=w;cells.forEach(function(c){c.style.cssText='width:'+cs+'px;height:'+cs+'px;background:#35373d;left:0;top:0;color:#142b36;font-size:'+cs*.45+'px'})}gr.forEach(function(r,y){r.forEach(function(v,x){var c=cells[y*4+x];c.style.transform='translate('+(8+x*(cs+6))+'px,'+(8+y*(cs+6))+'px)';if(c.textContent!==(v?String(v):'')){c.textContent=v||'';c.style.background=col[v]||'#3c3a32';c.style.color=v>128?'#fff4ed':'#142b36';c.style.fontSize=cs*(v>100?.34:.45)+'px'}})});saveBest('2048',sco);var label='Score '+sco;if(!sc.firstChild){sc.appendChild(document.createTextNode(label));var retry=el('button','','Restart');retry.onclick=reset;sc.appendChild(retry)}else sc.firstChild.textContent=label}
st.append(sc,bx,el('div','sc','Swipe the board or use arrow keys'));reset=roundReset(reset);reset();keyf=function(k){var m={ArrowLeft:'L',ArrowRight:'R',ArrowUp:'U',ArrowDown:'D'}[k];if(m)mv(m)};swipe(bx,mv)}],
['Flappy Dragon',function(){var cv=el('canvas','g');cv.width=300;cv.height=420;var c=cv.getContext('2d'),y,v,ps,sco,dead,running,last=0,spawn=0,elapsed=0,best=0,coins=0,sc=el('div','sc');var dragonImg=new Image();dragonImg.src=document.querySelector('.fl.dr img').src;try{best=+localStorage.getItem('terraform-flappy-best')||0}catch(e){}
var bg=document.createElement('canvas');bg.width=300;bg.height=420;var bc=bg.getContext('2d'),sky=bc.createLinearGradient(0,0,0,420);sky.addColorStop(0,'#100e21');sky.addColorStop(.7,'#3b2454');sky.addColorStop(1,'#796377');bc.fillStyle=sky;bc.fillRect(0,0,300,420);for(var star=0;star<45;star++){bc.fillStyle=star%3?'#9c7daa':'#ead3ed';bc.fillRect((star*73)%300,(star*113)%360,star%3?1:2,1)}bc.fillStyle='#b6a5c430';bc.beginPath();bc.arc(238,75,27,0,Math.PI*2);bc.fill();for(var t=0;t<7;t++){bc.fillStyle='#241b3b';bc.fillRect(t*51-8,270-t%3*42,15,140)}bc.fillStyle='#958a6a';bc.beginPath();bc.moveTo(0,402);bc.lineTo(45,390);bc.lineTo(110,400);bc.lineTo(180,385);bc.lineTo(250,396);bc.lineTo(300,390);bc.lineTo(300,420);bc.lineTo(0,420);bc.fill();for(var g=0;g<70;g++){bc.fillStyle=g%2?'#b1a67a':'#6b634e';bc.fillRect(g*43%300,405+g*13%15,5,2)}
var tex=document.createElement('canvas');tex.width=40;tex.height=36;var tc=tex.getContext('2d');tc.fillStyle='#20192f';tc.fillRect(0,0,40,36);tc.fillStyle='#4b3659';tc.fillRect(0,0,5,36);tc.fillStyle='#35253f';tc.fillRect(7,3,19,8);tc.fillRect(17,16,20,7);tc.fillRect(5,28,12,6);tc.fillStyle='#664969';tc.fillRect(8,4,12,2);tc.fillRect(20,17,13,1);
function drawDragon(now){var f=.5+.5*Math.sin(now/1000*(running?8:3.5));c.save();c.translate(-30,-29);for(var y=0;y<430;y+=4){var top=Math.max(0,1-y/290),sx=1-.075*f*top,dx=(1-sx)*214.5+Math.sin(now/700)*4*Math.exp(-Math.pow((y-130)/115,2));c.drawImage(dragonImg,0,y,429,Math.min(4,430-y),dx*60/429,y*60/429,60*sx,4.2*60/429)}c.restore()}
function reset(){y=190;v=0;ps=[];sco=0;coins=0;dead=false;running=false;spawn=0;elapsed=0;last=0}function flap(){if(dead){reset();raf=requestAnimationFrame(loop)}running=true;v=-230}
cv.addEventListener('pointerdown',function(e){e.preventDefault();flap()});keyf=function(k){if(k==' '||k=='ArrowUp')flap()};function tower(x,top,bottom){var h=bottom-top;c.save();c.beginPath();c.rect(x,top,40,h);c.clip();for(var j=top;j<bottom;j+=36)c.drawImage(tex,x,j);c.restore();c.fillStyle='#a188ae';c.fillRect(x-2,top,44,3);c.fillStyle='#100e2055';c.fillRect(x+35,top,5,h)}
function loop(now){if(document.hidden){last=now;raf=requestAnimationFrame(loop);return}if(last&&now-last<15){raf=requestAnimationFrame(loop);return}var dt=Math.min(.05,(now-last)/1000||.033);last=now;if(running&&!dead){elapsed+=dt;v+=620*dt;y+=v*dt;var speed=Math.min(155,82+sco*3+elapsed*.3);spawn-=dt;if(spawn<=0){ps.push({x:330,g:ps.length===0&&sco===0?195:Math.max(125,Math.min(285,(ps.length?ps[ps.length-1].g:200)+(Math.random()-.5)*105)),gap:Math.max(132,162-sco*1.2)});spawn=210/speed}ps.forEach(function(p){p.x-=speed*dt;if(!p.s&&p.x+40<50){p.s=true;sco++;buzz('win')}if(!p.coin&&Math.abs(p.x+20-64)<25&&Math.abs(p.g-(y+11))<34){p.coin=true;coins++;buzz('win')}if(p.x<79&&p.x+40>50&&(y<p.g-p.gap/2||y+22>p.g+p.gap/2))dead=true});ps=ps.filter(function(p){return p.x>-50});if(y<0||y+22>399)dead=true;if(dead){buzz('over');best=Math.max(best,sco);saveBest('Flappy Dragon',best);try{localStorage.setItem('terraform-flappy-best',best)}catch(e){}}}
c.drawImage(bg,0,0);ps.forEach(function(p){tower(p.x,0,p.g-p.gap/2);tower(p.x,p.g+p.gap/2,420);if(p.coin)return;var yy=p.g;c.fillStyle='#e5bd6b2b';c.beginPath();c.arc(p.x+20,yy,19,0,Math.PI*2);c.fill();c.save();c.translate(p.x+20,yy);c.rotate(Math.PI/4);c.fillStyle='#edc66e';c.fillRect(-7,-7,14,14);c.strokeStyle='#fff0ba';c.strokeRect(-7,-7,14,14);c.fillStyle='#bf7a43';c.fillRect(-3,-3,6,6);c.fillStyle='#fff5cc';c.fillRect(-5,-5,3,3);c.restore()});
if(dragonImg.complete&&dragonImg.naturalWidth){c.save();c.translate(64,y+11+(running?0:Math.sin(now/400)*4));c.rotate(Math.max(-.22,Math.min(.6,v*.002)));drawDragon(now);c.restore()}else{c.fillStyle='#a352cc';c.fillRect(50,y,28,22)}c.fillStyle='#eee2f5';c.font='bold 28px monospace';c.textAlign='center';c.fillText(sco,150,44);if(!running||dead){c.fillStyle='#100e21cc';c.beginPath();c.roundRect(32,124,236,105,16);c.fill();c.fillStyle='#e7cee9';c.font='bold 18px monospace';c.fillText(dead?'FLIGHT ENDED':'ENDER FLIGHT',150,155);c.fillStyle='#bda7ca';c.font='12px monospace';c.fillText(dead?'Score '+sco+' · Coins '+coins+' · Best '+best:'Tap to begin gently',150,183);c.fillText(dead?'Tap to fly again':'Tap or Space to flap',150,207)}var label=dead?'Score '+sco+' · Coins '+coins+' · Best '+best+' · Tap to retry':running?'Score '+sco+' · Coins '+coins+' · Speed rises gradually':'Tap to start · Collect floating coins';if(sc.textContent!==label)sc.textContent=label;if(!dead)raf=requestAnimationFrame(loop)}reset=roundReset(reset);reset();st.append(sc,cv);raf=requestAnimationFrame(loop)}],
['Minesweeper',function(){var N=8,K=10,m,r,f,fm=0,over=0,sc=el('div','sc'),g=el('div','bd ms');
function reset(){m=Array(64).fill(0);r=Array(64).fill(0);f=Array(64).fill(0);over=0;var c=0;while(c<K){var i=Math.random()*64|0;if(!m[i]){m[i]=1;c++}}draw()}
function nb(i){var o=[],x=i%N,y=i/N|0;for(var dy=-1;dy<2;dy++)for(var dx=-1;dx<2;dx++){var a=x+dx,b=y+dy;if((dx||dy)&&a>=0&&b>=0&&a<N&&b<N)o.push(b*N+a)}return o}
function cnt(i){return nb(i).filter(function(j){return m[j]}).length}
function open(i){if(r[i]||f[i])return;r[i]=1;if(!m[i]&&!cnt(i))nb(i).forEach(open)}
function draw(){g.innerHTML='';var lost=0,won=0,cl=['','#6ec6ff','#7be08a','#ff7a7a','#a98bff','#ff9e5e','#5fe0d0','#fff','#aaa'];if(over==1)lost=1;
m.forEach(function(x,i){var t='',cls=r[i]?'o':'';if(r[i]){t=m[i]?art('bomb'):(cnt(i)||'')}else if(f[i])t=art('flag');else if(over==1&&m[i])t=art('bomb');var b=el('button',cls,t);if(r[i]&&!m[i]&&cnt(i))b.style.color=cl[cnt(i)];
b.onclick=function(){if(over)return;if(fm){if(!r[i])f[i]=!f[i]}else{if(f[i])return;if(m[i]){over=1;buzz('over')}else open(i)}if(!over&&m.every(function(x,j){return x||r[j]})){over=2;victory()}draw()};g.appendChild(b)});
sc.innerHTML=(over==1?'Boom! You lost':over==2?'You cleared it!':'Mines: '+K)+'<button id="fb">'+(fm?'Flag mode: ON':'Flag mode: OFF')+'</button><button>Restart</button>';sc.querySelectorAll('button')[0].onclick=function(){fm=!fm;draw()};sc.querySelectorAll('button')[1].onclick=reset}
reset=roundReset(reset);reset();st.append(sc,g,el('div','sc','Tap to dig. Turn flag mode on to mark mines.'))}]

,['Whack-a-Creeper',function(){var sc=el('div','sc'),g=el('div','bd t3'),t=0,pts=0,left=0,pos=-1,run=0,creepButtons=[];
function draw(){if(!creepButtons.length){for(var i=0;i<9;i++){(function(i){var b=el('button','','');b.onclick=function(){if(run&&pos===i){pts++;buzz('hit');pos=-1;draw();info()}};g.appendChild(b);creepButtons.push(b)})(i)}}creepButtons.forEach(function(b,i){if(b.dataset.show!==String(pos===i)){b.innerHTML=pos===i?art('creeper'):'';b.dataset.show=String(pos===i)}})}
function info(){saveBest('Whack-a-Creeper',pts);sc.innerHTML=(run?'Time '+left+'s':left==0&&t?'Time up!':'Tap the creeper')+' - Hits '+pts+'<button>'+(run?'Running':'Start')+'</button>';sc.querySelector('button').onclick=start}
function start(){if(run)return;if(t)nextRound();pts=0;left=20;run=1;t=1;var began=0,previous=0,next=0;function whackLoop(now){if(!began){began=now;next=now+600}if(document.hidden){began+=now-previous;next+=now-previous}else{var oldLeft=left,oldPos=pos;left=Math.max(0,20-Math.floor((now-began)/1000));if(left<=0){run=0;pos=-1;if(pts>0)victory();else buzz('over')}else if(now>=next){pos=Math.random()*9|0;next=now+850}if(oldPos!==pos)draw();if(oldLeft!==left)info()}previous=now;if(run)raf=requestAnimationFrame(whackLoop)}raf=requestAnimationFrame(whackLoop)}
draw();info();st.append(sc,g)}],
['Reaction Test',function(){var b=el('button','mini','Tap to start'),sc=el('div','sc','Wait for green, then tap fast'),s=0,w=0,to,best=0,attempts=0;b.style.cssText='width:min(88vw,320px);height:220px;font-size:20px;border-radius:16px;background:#2a2a36;color:#fff;margin:0';
b.onclick=function(){if(w==0){if(attempts++)nextRound();w=1;b.style.background='#c0392b';b.textContent='Wait...';to=later(function(){w=2;s=performance.now();b.style.background='#27ae60';b.classList.remove('wait');b.classList.add('go');b.innerHTML='<div class="reaction-orb">⚡</div>TAP!'},1200+Math.random()*2500)}
else if(w==1){clearTimeout(to);w=0;buzz('over');b.style.background='#2a2a36';b.textContent='Too early! Tap to retry'}
else{var ms=Math.round(performance.now()-s);w=0;var personalBest=!best||ms<best;best=best?Math.min(best,ms):ms;saveBest('Reaction Test',best,true);if(personalBest)victory();else buzz('win');b.style.background='#2a2a36';b.textContent=ms+' ms - tap to retry';sc.textContent='Best '+best+' ms'}};
b.classList.add('reactpanel');function rlabel(text){b.innerHTML='<div class="reaction-orb">◎</div>'+text}rlabel('Tap to start');var raw=b.onclick;b.onclick=function(){raw();b.classList.toggle('wait',w===1);b.classList.toggle('go',w===2);rlabel(b.textContent.replace(/^◎/,''));};st.append(sc,b)}],
['Rock Paper Scissors',function(){var o=['rock','paper','scissors'].map(art),nm=['Rock','Paper','Scissors'],w=0,l=0,plays=0,sc=el('div','sc'),out=el('div','',''),r=el('div','dp');out.style.cssText='font-size:64px;text-align:center;min-height:90px';
function info(m){saveBest('Rock Paper Scissors',w);sc.textContent='Wins '+w+' - Losses '+l;if(m)out.innerHTML=m}
o.forEach(function(e,i){var b=el('button','',e);b.className='choice';b.innerHTML=e+'<span>'+nm[i]+'</span>';b.onclick=function(){if(plays++)nextRound();var c=Math.random()*3|0,res=i==c?'Draw':(i-c+3)%3==1?'You win':'You lose';if(res=='You win'){w++;victory()}if(res=='You lose')l++;if(res!=='You win')buzz(res==='You lose'?'over':'hit');info('<div class="duel">'+e+'<span style="font-size:13px;color:#7693ad">VS</span>'+o[c]+'</div><div class="result">'+res+'</div>')};r.appendChild(b)});
info('<div style="font:18px monospace;color:#afc8df;padding:30px">Choose your move</div>');st.append(sc,out,r)}],['Terraform',function(){
var wrap=el('div','bw'),bar=el('div','bwbar'),cv=el('canvas','bwc'),ctx=cv.getContext('2d',{alpha:false}),msg=el('div','bwmsg','TERRAFORM · Left stick: move. ⇈: jump. Hold right stick or terrain to mine/build. ☀: torch.'),ctrl=el('div','bwcontrols');
var W=180,H=64,T=20,world=new Uint8Array(W*H),px=14*T,py=12*T,vx=0,vy=0,ground=false,held={},mode='mine',selected=1,inv={1:0,2:0,3:0,4:0,5:0},camera=0,last=0,active=true,dirty=true,saveTimer=0,aimX=3,aimY=0,started=false,coyote=0,jumpLatch=false,face=1,camY=null,particles=[],mineTarget=null,mineTime=0,lastAction=0,hp=100,hitCooldown=0,dayClock=60,slimes=[],spawnTime=0,kills=0,swing=0;
var colors=['','#795035','#5d8730','#727888','#d59b40','#966b42'],names=['','Dirt','Grass','Stone','Gold','Wood'];
var atlas=[];for(var b=1;b<=5;b++){var tile=document.createElement('canvas');tile.width=tile.height=T;var tc=tile.getContext('2d');tc.fillStyle=colors[b];tc.fillRect(0,0,T,T);for(var j=0;j<25;j++){var xx=((j*73+j*j*19+b*17)%97)%T,yy=((j*41+j*j*7+b*13)%89)%T;tc.fillStyle=b===3?(j%2?'#9295a0':'#555d70'):b===5?(j%2?'#b47a42':'#714c2b'):(j%2?'#895b3c':'#68452f');tc.fillRect(xx,yy,b===5?2:3,b===5?8:2)}if(b===2){tc.fillStyle='#427329';tc.fillRect(0,0,T,6);tc.fillStyle='#77b84c';tc.fillRect(0,0,T,2);for(var j=0;j<5;j++){tc.fillRect(j*4,2,2,5+(j%2)*2)}}if(b===4){tc.fillStyle='#7d6255';tc.fillRect(0,0,T,T);tc.fillStyle='#f9c647';tc.fillRect(3,4,4,4);tc.fillRect(12,9,5,5);tc.fillRect(6,15,3,3);tc.fillStyle='#fff3a2';tc.fillRect(4,4,2,2);tc.fillRect(13,9,2,2)}tc.fillStyle='#00000008';tc.fillRect(T-2,0,2,T);tc.fillRect(0,T-2,T,2);if(b===2){tc.fillStyle='#b0da68';for(var z=0;z<4;z++)tc.fillRect(2+z*5,0,1,3)}atlas[b]=tile}
var torches=[];try{torches=JSON.parse(localStorage.getItem('terraform-torches')||'[]')}catch(e){}
var terrainCache=new Map();function at(x,y){return x<0||x>=W||y<0||y>=H?3:world[y*W+x]}function put(x,y,b){if(x>=0&&x<W&&y>=0&&y<H){world[y*W+x]=b;terrainCache.delete(Math.floor(x/16));terrainCache.delete(Math.floor((x-1)/16));terrainCache.delete(Math.floor((x+1)/16))}}
function generate(){terrainCache.clear();world.fill(0);for(var x=0;x<W;x++){var h=23+Math.round(Math.sin(x*.11)*3+Math.sin(x*.31)*2);for(var y=h;y<H;y++){var b=y===h?2:y<h+5?1:3;if(y>h+7&&Math.sin(x*.27+y*.41)+Math.cos(x*.43-y*.23)>1.45)b=0;if(b===3&&Math.random()<.055)b=4;put(x,y,b)}if(x>5&&x%17===0){for(var j=1;j<=4;j++)put(x,h-j,5);for(var a=-2;a<=2;a++)for(var b=-6;b<=-4;b++)if(Math.abs(a)+Math.abs(b+5)<4)put(x+a,h+b,2)}}px=14*T;py=10*T;vy=0;inv={1:12,2:0,3:0,4:0,5:8};dirty=true}
function save(){try{localStorage.setItem('roshan-blockworld-v1',JSON.stringify({w:Array.from(world),px:px,py:py,inv:inv,hp:hp,day:dayClock,kills:kills}));dirty=false}catch(e){}}
try{var old=JSON.parse(localStorage.getItem('roshan-blockworld-v1'));if(old&&old.w.length===W*H){world.set(old.w);px=old.px;py=old.py;inv=old.inv;hp=old.hp||100;dayClock=old.day||60;kills=old.kills||0;dirty=false}else generate()}catch(e){generate()}
function button(text,fn){var b=el('button','',text);b.onclick=fn;bar.appendChild(b);return b}
var modeBtn=button('Mine',function(){mode=mode==='mine'?'build':'mine';modeBtn.textContent=mode==='mine'?'Mine':'Build';msg.textContent=mode==='mine'?'Tap a nearby block to mine.':'Tap an empty nearby space to build.'});
var select=document.createElement('select');[1,3,5,2,4].forEach(function(n){var o=document.createElement('option');o.value=n;o.textContent=names[n];select.appendChild(o)});select.onchange=function(){selected=+select.value};bar.appendChild(select);
var stats=el('div','tfstats','');wrap.appendChild(stats);var bag=el('span','','');bar.appendChild(bag);var hotbar=el('div','tfhotbar');[1,3,5,2,4].forEach(function(n){var b=el('button','',names[n]);var icon=document.createElement('canvas');icon.width=icon.height=20;icon.getContext('2d').drawImage(atlas[n],0,0);b.prepend(icon);b.dataset.block=n;b.onclick=function(){selected=n;select.value=n;[].forEach.call(hotbar.children,function(e){e.classList.remove('sel')});b.classList.add('sel')};if(n===1)b.classList.add('sel');hotbar.appendChild(b)});
button('Fullscreen',async function(){try{if(!document.fullscreenElement){await wrap.requestFullscreen();try{await screen.orientation.lock('landscape')}catch(e){msg.textContent='Rotate your phone sideways. Orientation lock is not supported here.'}}else await document.exitFullscreen()}catch(e){msg.textContent='Fullscreen is unavailable in this browser. Rotate sideways to play.'}});
button('Heal',function(){if((inv[4]||0)>=2&&hp<100){inv[4]-=2;hp=Math.min(100,hp+35);dirty=true;msg.textContent='Used 2 gold to heal.'}else msg.textContent='Heal needs 2 gold and missing health.'});button('New world',function(){if(confirm('Start a new world? This replaces your saved world.')){nextRound();generate();hp=100;slimes=[];torches=[];dayClock=60;kills=0;try{localStorage.setItem('terraform-torches','[]')}catch(e){}save()}});
function resize(){var r=wrap.getBoundingClientRect(),full=wrap===document.fullscreenElement,h=full?Math.max(120,innerHeight-bar.offsetHeight-msg.offsetHeight-20):Math.max(240,Math.min(420,innerHeight-190));var ww=Math.max(280,Math.floor(r.width-(full?16:0)));if(cv.width!==ww)cv.width=ww;if(cv.height!==h)cv.height=h;cv.style.height=h+'px'}
wrap.append(bar,msg,hotbar,cv,ctrl);st.appendChild(wrap);var resizeTimeout=0;function resizeSoon(){clearTimeout(resizeTimeout);resizeTimeout=setTimeout(resize,100)}window.addEventListener('resize',resizeSoon);document.addEventListener('fullscreenchange',resize);
function control(label,key){var b=el('button','',label);function up(){held[key]=false}b.onpointerdown=function(e){held[key]=true;b.setPointerCapture(e.pointerId);e.preventDefault()};b.onpointerup=up;b.onpointercancel=up;ctrl.appendChild(b)}var joy=el('div','tfjoy','<span>✥</span>');ctrl.appendChild(joy);function steer(e){var r=joy.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2;held.L=dx<-12;held.R=dx>12;held.J=e.clientY<r.top+25;joy.firstChild.style.transform='translate('+Math.max(-22,Math.min(22,dx))+'px,0)'}joy.onpointerdown=function(e){joy.setPointerCapture(e.pointerId);steer(e);e.preventDefault()};joy.onpointermove=function(e){if(joy.hasPointerCapture(e.pointerId))steer(e)};joy.onpointerup=joy.onpointercancel=function(){held.L=held.R=held.J=false;joy.firstChild.style.transform=''};control('⇈','J');var action=el('div','tfaim','<span>⛏</span>');ctrl.appendChild(action);action.onpointerdown=function(e){action.setPointerCapture(e.pointerId);aim(e);mineTarget={aim:true};mineTime=0;e.preventDefault()};function aim(e){var r=action.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,d=Math.max(1,Math.hypot(dx,dy));aimX=dx/d*3;aimY=dy/d*3;action.firstChild.style.transform='translate('+dx/d*18+'px,'+dy/d*18+'px)'}action.onpointermove=function(e){if(action.hasPointerCapture(e.pointerId))aim(e)};action.onpointerup=function(){if(mineTime<.12)useTile(Math.floor(px/T+aimX),Math.floor(py/T+aimY));mineTarget=null;mineTime=0;action.firstChild.style.transform=''};action.onpointercancel=function(){mineTarget=null;mineTime=0;action.firstChild.style.transform=''};var torch=el('button','tftorch','☀');torch.onclick=function(){var x=Math.floor(px/T),y=Math.floor(py/T);if(!torches.some(function(t){return t.x===x&&t.y===y})){torches.push({x:x,y:y});try{localStorage.setItem('terraform-torches',JSON.stringify(torches))}catch(e){}}};ctrl.appendChild(torch);var sword=el('button','tfsword','⚔');sword.onclick=function(){swing=.25;slimes.forEach(function(en){if(en.hp>0&&Math.abs(en.x-px)<75&&Math.abs(en.y-py)<65){en.hp--;en.vx=face*100;en.vy=-100;burst(Math.floor(en.x/T),Math.floor(en.y/T),2);if(en.hp<=0){buzz('win');kills++;inv[4]=(inv[4]||0)+1;dirty=true}}})};ctrl.appendChild(sword);resize();
function keydown(e){if({ArrowLeft:1,ArrowRight:1,ArrowUp:1,' ':1,a:1,d:1,w:1}[e.key]){held[{ArrowLeft:'L',a:'L',ArrowRight:'R',d:'R',ArrowUp:'J',w:'J',' ':'J'}[e.key]]=true;e.preventDefault()}}function keyup(e){held[{ArrowLeft:'L',a:'L',ArrowRight:'R',d:'R',ArrowUp:'J',w:'J',' ':'J'}[e.key]]=false}window.addEventListener('keydown',keydown);window.addEventListener('keyup',keyup);
function solid(x,y){for(var by=Math.floor(y/T);by<=Math.floor((y+27)/T);by++)for(var bx=Math.floor(x/T);bx<=Math.floor((x+13)/T);bx++)if(at(bx,by))return true;return false}function moveAxis(n,horizontal){var step=Math.sign(n),remaining=Math.abs(n);while(remaining>0){var d=step*Math.min(1,remaining),xx=px+(horizontal?d:0),yy=py+(horizontal?0:d);if(solid(xx,yy)){if(!horizontal){if(n>0)ground=true;vy=0}return}if(horizontal)px=xx;else py=yy;remaining-=Math.abs(d)}}function burst(x,y,b){if(particles.length>30)return;for(var i=0;i<(window.roshanLowPower?1:4);i++)particles.push({x:x*T+10,y:y*T+10,vx:(Math.random()-.5)*100,vy:-30-Math.random()*80,t:.4,c:colors[b]})}
function useTile(x,y){if(!started||x<0||x>=W||y<0||y>=H)return;if(Math.hypot((x+.5)*T-px,(y+.5)*T-py)>T*6){msg.textContent='Walk closer to mine or build.';return}var b=at(x,y);if(mode==='mine'&&b){burst(x,y,b);put(x,y,0);inv[b]=(inv[b]||0)+1;buzz('hit');msg.textContent='Collected '+names[b]+'. Gold found: '+(inv[4]||0)}else if(mode==='build'&&!b){if(!at(x-1,y)&&!at(x+1,y)&&!at(x,y-1)&&!at(x,y+1)){msg.textContent='Build next to an existing block.';return}if((inv[selected]||0)<=0){msg.textContent='Mine some '+names[selected].toLowerCase()+' first.';return}put(x,y,selected);if(solid(px,py))put(x,y,0);else{inv[selected]--;burst(x,y,selected);msg.textContent='Placed '+names[selected]}}dirty=true;swing=.22;lastAction=performance.now()}
cv.onpointerdown=function(e){var r=cv.getBoundingClientRect(),x=Math.floor((e.clientX-r.left+camera)/T),y=Math.floor((e.clientY-r.top+(camY||0))/T);cv.setPointerCapture(e.pointerId);mineTarget={x:x,y:y};mineTime=0;e.preventDefault()};cv.onpointerup=function(){if(mineTarget&&!mineTarget.aim&&mineTime<.12)useTile(mineTarget.x,mineTarget.y);mineTarget=null;mineTime=0};cv.onpointercancel=function(){mineTarget=null;mineTime=0};
function terrainChunk(idx){if(terrainCache.has(idx))return terrainCache.get(idx);var layer=document.createElement('canvas');layer.width=16*T;layer.height=H*T;var ctx=layer.getContext('2d'),x0=idx*16,x1=Math.min(W,x0+16),y0=0,y1=H;for(var y=y0;y<y1;y++)for(var x=x0;x<x1;x++){var b=at(x,y);if(!b)continue;var sx=x*T-idx*16*T,sy=y*T;if(b===2&&(at(x,y+1)===0||at(x,y+1)===2||at(x,y+1)===5)){ctx.fillStyle='#285836';ctx.fillRect(sx+(!at(x-1,y)?3:0),sy+(!at(x,y-1)?3:0),T-(!at(x-1,y)?3:0)-(!at(x+1,y)?3:0),T-(!at(x,y-1)?3:0));ctx.fillStyle='#397638';ctx.fillRect(sx+3,sy+4,14,12);ctx.fillStyle='#5f9b43';for(var lf=0;lf<9;lf++)ctx.fillRect(sx+2+(lf*7+x*3)%15,sy+3+(lf*11+y)%13,3,2);ctx.fillStyle='#8bb954';ctx.fillRect(sx+5,sy+4,4,2);if(!at(x,y-1)){ctx.fillRect(sx+2,sy+2,4,2);ctx.fillRect(sx+13,sy+1,4,3)}}else{ctx.drawImage(atlas[b],sx,sy);if(!at(x-1,y)){ctx.fillStyle='#bba58944';ctx.fillRect(sx,sy,2,T)}if(!at(x+1,y)){ctx.fillStyle='#17212b55';ctx.fillRect(sx+T-2,sy,2,T)}if(!at(x,y+1)){ctx.fillStyle='#13213277';ctx.fillRect(sx,sy+T-2,T,2)}if(b===2&&!at(x,y-1)){ctx.fillStyle='#7ba848';for(var blade=0;blade<4;blade++)ctx.fillRect(sx+2+blade*5,sy-2-(x+blade)%3,1,4);if(x%9===3){ctx.fillStyle='#3c7538';ctx.fillRect(sx+9,sy-8,1,8);ctx.fillStyle=x%2?'#e8bd72':'#db8daa';ctx.fillRect(sx+7,sy-9,5,3);ctx.fillStyle='#f8db83';ctx.fillRect(sx+9,sy-9,1,1)}}}}
terrainCache.set(idx,layer);return layer}
function loop(now){if(!active)return;if(now-last<15){raf=requestAnimationFrame(loop);return}var dt=Math.min(.035,(now-last)/1000||.016);last=now;if(!document.hidden){dayClock=(dayClock+dt)%240;hitCooldown=Math.max(0,hitCooldown-dt);swing=Math.max(0,swing-dt);var targetV=(held.R?145:0)-(held.L?145:0);vx+=(targetV-vx)*Math.min(1,dt*(ground?18:9));if(Math.abs(vx)<.5)vx=0;if(vx)face=vx>0?1:-1;coyote=ground?.11:Math.max(0,coyote-dt);if(held.J&&!jumpLatch&&coyote>0){vy=-285;ground=false;coyote=0}if(!held.J&&vy<-100)vy+=900*dt;jumpLatch=!!held.J;vy=Math.min(420,vy+700*dt);ground=false;moveAxis(vx*dt,true);moveAxis(vy*dt,false);px=Math.max(1,Math.min(W*T-16,px));py=Math.max(0,py);
var targetCam=Math.max(0,Math.min(W*T-cv.width,px-cv.width*.4));camera+=(targetCam-camera)*Math.min(1,dt*9);var targetCy=Math.max(0,Math.min(H*T-cv.height,py-cv.height*.48));if(camY===null)camY=targetCy;else camY+=(targetCy-camY)*Math.min(1,dt*9);var cy=camY;
if(mineTarget){mineTime+=dt;var mx=mineTarget.aim?Math.floor(px/T+aimX):mineTarget.x,my=mineTarget.aim?Math.floor(py/T+aimY):mineTarget.y;var hardness=mode==='build'?.18:at(mx,my)===3?.38:at(mx,my)===4?.5:.22;if(mineTime>=hardness){useTile(mx,my);mineTime=0}}
var night=dayClock>150;ctx.imageSmoothingEnabled=false;ctx.fillStyle=night?'#162440':'#70b7ea';ctx.fillRect(0,0,cv.width,cv.height);ctx.fillStyle=night?'#e1e9f7':'#fff0af';ctx.fillRect(80-camera*.08,28-cy*.05,24,24);if(night){ctx.fillStyle='#a4b9e1';for(var st=0;st<40;st++)ctx.fillRect(st*73%cv.width,st*41%140,1,1)}ctx.fillStyle=night?'#38465e':'#e2eff7';for(var cl=0;cl<7;cl++){var xx=(cl*170-camera*.15)%(cv.width+180),yy=40+(cl%3)*18-cy*.08;ctx.fillRect(xx,yy,55,8);ctx.fillRect(xx+12,yy-6,30,8)}for(var layer=0;layer<2;layer++){ctx.fillStyle=night?(layer?'#223c51':'#2c405a'):(layer?'#679488':'#92b1b4');for(var m=0;m<12;m++){var xx=m*160-camera*(.12+layer*.1),base=cv.height*.65+layer*35-cy*.12;ctx.beginPath();ctx.moveTo(xx-90,cv.height);ctx.lineTo(xx-50,base+40);ctx.lineTo(xx-30,base-55);ctx.lineTo(xx+20,base-75);ctx.lineTo(xx+50,base-15);ctx.lineTo(xx+110,cv.height);ctx.fill()}}
for(var tr=0;tr<18;tr++){var tx=tr*111-camera*.23,ty=cv.height*.8-cy*.22;ctx.fillStyle=night?'#1d3444':'#658d80';ctx.fillRect(tx+12,ty-95,6,110);for(var branch=0;branch<5;branch++){var ww=24+branch*7;ctx.fillRect(tx+15-ww/2,ty-125+branch*20,ww,13);ctx.fillRect(tx+9-ww/2,ty-118+branch*20,ww+12,6)}}
var firstChunk=Math.max(0,Math.floor(camera/(16*T))),lastChunk=Math.min(Math.ceil(W/16)-1,Math.floor((camera+cv.width)/(16*T)));terrainCache.forEach(function(layer,key){if(key<firstChunk-1||key>lastChunk+1)terrainCache.delete(key)});for(var chunk=firstChunk;chunk<=lastChunk;chunk++){var layer=terrainChunk(chunk),cropY=Math.max(0,Math.floor(cy)),cropH=Math.min(layer.height-cropY,cv.height);ctx.drawImage(layer,0,cropY,layer.width,cropH,Math.floor(chunk*16*T-camera),cropY-cy,layer.width,cropH)}
spawnTime+=dt;if(spawnTime>9&&slimes.length<4){spawnTime=0;var ex=Math.max(2,Math.min(W-3,Math.floor(px/T)+(Math.random()<.5?-1:1)*(12+Math.random()*7|0))),ey=0;while(ey<H-2&&!at(ex,ey+1))ey++;slimes.push({x:ex*T,y:ey*T-14,vx:0,vy:0,jump:1,hp:3})}
slimes=slimes.filter(function(en){if(en.hp<=0)return false;en.jump-=dt;en.vy=Math.min(360,en.vy+600*dt);var bottom=at(Math.floor((en.x+9)/T),Math.floor((en.y+14+en.vy*dt)/T));if(bottom){en.vy=0;en.y=Math.floor((en.y+14)/T)*T-14;if(en.jump<=0){en.vy=-175;en.vx=en.x<px?48:-48;en.jump=1.4}}else en.y+=en.vy*dt;if(!at(Math.floor((en.x+(en.vx>0?19:0)+en.vx*dt)/T),Math.floor((en.y+7)/T)))en.x+=en.vx*dt;
if(Math.abs(en.x-px)<21&&Math.abs(en.y-py)<29&&hitCooldown===0){buzz('hit');hp=Math.max(0,hp-10);hitCooldown=1.3;vx=en.x<px?170:-170;vy=-110;dirty=true;if(hp===0){buzz('over');nextRound();hp=100;px=14*T;py=10*T;vx=vy=0;slimes.forEach(function(e){e.hp=0});hitCooldown=3;camY=null;msg.textContent='Respawned at home. Inventory kept.'}}
var ex=en.x-camera,ey=en.y-cy;ctx.fillStyle=night?'#8d69a8':'#459778';ctx.fillRect(ex+2,ey+3,16,11);ctx.fillRect(ex+5,ey,10,4);ctx.fillStyle='#a8dcad';ctx.fillRect(ex+4,ey+3,5,2);ctx.fillStyle='#152b35';ctx.fillRect(ex+5,ey+7,2,2);ctx.fillRect(ex+13,ey+7,2,2);return en.hp>0});
var sx=Math.floor(px-camera),sy=Math.floor(py-cy);ctx.globalAlpha=hitCooldown>0&&Math.floor(now/90)%2?.4:1;ctx.fillStyle='#293348';ctx.fillRect(sx+2,sy-3,10,6);ctx.fillRect(sx,sy,4,7);ctx.fillStyle='#f1bc92';ctx.fillRect(sx+4,sy+2,8,7);ctx.fillStyle='#1d2135';ctx.fillRect(sx+(face>0?10:4),sy+4,2,2);ctx.fillStyle='#724936';ctx.fillRect(sx+2,sy-3,10,3);ctx.fillRect(sx+(face>0?2:10),sy,2,7);ctx.fillStyle='#875d9b';ctx.fillRect(sx+2,sy+10,10,12);ctx.fillStyle='#c5a0d4';ctx.fillRect(sx+2,sy+10,3,10);ctx.fillStyle='#ebb184';ctx.fillRect(sx-1,sy+13,3,8);ctx.fillRect(sx+12,sy+13,3,8);var step=Math.abs(vx)>5?Math.floor(now/130)%2*3:0;ctx.fillStyle='#39475f';ctx.fillRect(sx+2,sy+22,4,5+step);ctx.fillRect(sx+8,sy+22,4,8-step);ctx.fillStyle='#222a3a';ctx.fillRect(sx+1,sy+27+step,5,2);ctx.fillRect(sx+8,sy+30-step,5,2);ctx.strokeStyle='#ffffff99';ctx.strokeRect(Math.floor((px/T+aimX)*T-camera),Math.floor((py/T+aimY)*T-cy),T,T);ctx.fillStyle='#69482b';ctx.fillRect(sx+15,sy+12,2,12);ctx.fillStyle='#b8c9d5';ctx.fillRect(sx+12,sy+10,9,3);ctx.fillStyle='#d1b971';ctx.fillRect(sx+1,sy+19,12,2);ctx.fillStyle='#283b58';ctx.fillRect(sx+4,sy+11,6,2);
ctx.globalAlpha=1;if(swing>0){ctx.strokeStyle='#dce6ed';ctx.lineWidth=2;ctx.beginPath();ctx.arc(sx+7,sy+12,22,-1.3+swing*7,1+swing*7);ctx.stroke();ctx.lineWidth=1}particles=particles.filter(function(p){p.t-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=240*dt;ctx.fillStyle=p.c;ctx.fillRect(p.x-camera,p.y-cy,3,3);return p.t>0});if(mineTarget){var mx=mineTarget.aim?Math.floor(px/T+aimX):mineTarget.x,my=mineTarget.aim?Math.floor(py/T+aimY):mineTarget.y;ctx.strokeStyle='#ffeb9e';ctx.strokeRect(mx*T-camera,my*T-cy,T,T);ctx.fillStyle='#ffefaf';ctx.fillRect(mx*T-camera,my*T-cy-4,Math.min(T,mineTime*60),2);ctx.strokeStyle='#1d1826';ctx.beginPath();ctx.moveTo(mx*T-camera+3,my*T-cy+2);ctx.lineTo(mx*T-camera+9,my*T-cy+9);ctx.lineTo(mx*T-camera+5,my*T-cy+15);if(mineTime>.15){ctx.moveTo(mx*T-camera+9,my*T-cy+9);ctx.lineTo(mx*T-camera+17,my*T-cy+5)}ctx.stroke()}if(cy>T*17){ctx.fillStyle='rgba(6,12,28,'+Math.min(.7,(cy-T*17)/500)+')';ctx.fillRect(0,0,cv.width,cv.height)}torches.forEach(function(t){var tx=t.x*T-camera,ty=t.y*T-cy;if(tx<-70||tx>cv.width+70||ty<-70||ty>cv.height+70)return;ctx.fillStyle='#ffc45522';ctx.fillRect(tx-35,ty-35,80,80);ctx.fillStyle='#d99d48';ctx.fillRect(tx+6,ty+5,3,10);ctx.fillStyle='#ffcc43';ctx.fillRect(tx+3,ty,8,7);ctx.fillStyle='#fff5b6';ctx.fillRect(tx+5,ty,3,4)});var statText=Array(Math.ceil(hp/20)+1).join('♥')+' '+hp+'/100 · '+(night?'Night':'Day')+' · Slimes '+kills+' · Round '+rounds[currentGame];if(stats.textContent!==statText)stats.textContent=statText;[].forEach.call(hotbar.children,function(btn){var n=+btn.dataset.block;if(n){var label=names[n]+' '+(inv[n]||0);if(btn.lastChild.textContent!==label)btn.lastChild.textContent=label}});var text='Terraform · '+names[selected]+' '+(inv[selected]||0)+' · Gold '+(inv[4]||0);if(bag.textContent!==text)bag.textContent=text;saveTimer+=dt;if(dirty&&saveTimer>5){save();saveTimer=0}}
raf=requestAnimationFrame(loop)}
var startScreen=el('div','tfstart','<div><small>EXPLORE · MINE · BUILD</small><h2>TERRAFORM</h2><p>A pocket pixel sandbox. Your world saves on this device.</p><button type="button">START</button><p class="tfhelp">Left joystick: move · ⇈: jump<br>Right joystick: aim + hold to mine/build<br>Hotbar: choose a block · ☀: torch · ⚔: attack · Heal: 2 gold</p></div>');wrap.appendChild(startScreen);startScreen.querySelector('button').onclick=async function(){started=true;startScreen.remove();try{await wrap.requestFullscreen();try{await screen.orientation.lock('landscape')}catch(e){msg.textContent='Rotate phone sideways if needed. Landscape lock unavailable in this browser.'}}catch(e){msg.textContent='Fullscreen unavailable here. Rotate phone sideways to play.'}resize();last=performance.now();raf=requestAnimationFrame(loop)};
cleanup=function(){active=false;save();clearTimeout(resizeTimeout);terrainCache.clear();window.removeEventListener('resize',resizeSoon);document.removeEventListener('fullscreenchange',resize);window.removeEventListener('keydown',keydown);window.removeEventListener('keyup',keyup);if(document.fullscreenElement===wrap)document.exitFullscreen().catch(function(){});cleanup=null};
}]

];

function saveBest(name,value,lower){if(!Number.isFinite(value)||value<0)return;try{var data=JSON.parse(localStorage.getItem('roshan-arcade-bests')||'{}'),old=data[name];if(old==null||(lower?value<old:value>old)){data[name]=value;localStorage.setItem('roshan-arcade-bests',JSON.stringify(data))}}catch(e){}}
function profilePanel(){var box=el('section','arcprofile'),h=el('h3','','Your arcade'),note=el('p','','Saved on this device only. Clearing browser data clears this profile.');box.append(h,note);var data={},ach=[],last='';try{data=JSON.parse(localStorage.getItem('roshan-arcade-bests')||'{}');ach=JSON.parse(localStorage.getItem('f1-earned')||'[]');last=localStorage.getItem('roshan-arcade-last')||'';var f=+localStorage.getItem('terraform-flappy-best');if(f>0)data['Flappy Dragon']=Math.max(f,data['Flappy Dragon']||0)}catch(e){}var names={explorer:'Social explorer',dragon:'Dragon whisperer',win:'First victory'};var dl=el('dl');Object.keys(data).forEach(function(k){dl.append(el('dt','',k),el('dd','',String(data[k])+(k==='Reaction Test'?' ms':'')))});if(!Object.keys(data).length)box.append(el('p','','No scores yet. Play a round to start.'));else box.append(dl);box.append(el('p','','Last played: '+(last||'Not yet')),el('p','','Achievements: '+(ach.length?ach.map(function(k){return names[k]||k}).join(' · '):'None unlocked yet')));return box}
function picker(){stop();st.dataset.game='picker';tb.hidden=true;st.innerHTML='';var top=el('div','picktop','<div><small>CHOOSE YOUR NEXT ROUND</small><h2>Pick a game</h2></div>');var prof=el('button','','Your arcade');prof.type='button';top.append(prof);st.append(top);var panel=profilePanel();panel.hidden=true;prof.setAttribute('aria-expanded','false');prof.onclick=function(){panel.hidden=!panel.hidden;prof.setAttribute('aria-expanded',String(!panel.hidden))};st.append(panel);var grid=el('div','gamegrid'),icons=['leaf','sword','crystal','rock','moon','bomb','creeper','flame','scissors','flag'],hints=['A garden classic','Two players or solo','Find matching pairs','Merge your tiles','Fly between towers','Dig with care','A quick target game','Test your timing','Choose your move','Explore, mine, build'];games.forEach(function(g,i){var b=el('button','gamecard',art(icons[i])+'<b>'+g[0]+'</b><small>'+hints[i]+'</small>');b.type='button';b.onclick=function(){open(i)};grid.append(b)});st.append(grid)}

function open(i){stop();tb.hidden=true;try{localStorage.setItem('roshan-arcade-last',games[i][0])}catch(e){}currentGame=i;st.dataset.game=i;st.innerHTML='';roundLabel=el('span','','Round '+rounds[i]);var strip=el('div','roundstrip'),haptic=el('button','','Vibration: '+(!navigator.vibrate?'Unavailable':vibrationOn?'On':'Off'));haptic.type='button';haptic.disabled=!navigator.vibrate;haptic.setAttribute('aria-pressed',vibrationOn);haptic.onclick=function(){vibrationOn=!vibrationOn;haptic.textContent='Vibration: '+(vibrationOn?'On':'Off');haptic.setAttribute('aria-pressed',vibrationOn);try{localStorage.setItem('arcade-vibration',vibrationOn?'on':'off')}catch(e){}if(vibrationOn)buzz('win');else if(navigator.vibrate)navigator.vibrate(0)};var sound=el('button','','Sound: '+(cheerSound?'On':'Off'));sound.type='button';sound.setAttribute('aria-pressed',cheerSound);sound.onclick=function(){cheerSound=!cheerSound;sound.textContent='Sound: '+(cheerSound?'On':'Off');sound.setAttribute('aria-pressed',cheerSound);try{localStorage.setItem('arcade-cheer-sound',cheerSound?'on':'off')}catch(e){}if(cheerSound)unlockCheer();else{cheerNodes.forEach(function(node){try{node.stop()}catch(e){}});cheerNodes=[]}};var back=el('button','','All games');back.onclick=picker;strip.append(back,roundLabel,haptic,sound);st.appendChild(strip);cur=function(){open(i)};[].forEach.call(tb.children,function(b,j){b.className=j==i?'a':''});games[i][1]()}
games.forEach(function(g,i){var b=el('button','',g[0]);b.onclick=function(){open(i)};tb.appendChild(b)});
document.getElementById('gb').onclick=function(){gm.classList.add('on');document.body.classList.add('playing');hero.classList.add('off');document.body.style.overflow='hidden';picker()};
document.getElementById('gx').onclick=function(){gm.classList.remove('on');document.body.classList.remove('playing');hero.classList.toggle('off',hero.getBoundingClientRect().bottom<=0);document.body.style.overflow='';stop();st.innerHTML=''};
document.addEventListener('keydown',function(e){if(gm.classList.contains('on')&&keyf){if(e.key.indexOf('Arrow')==0||e.key==' ')e.preventDefault();keyf(e.key)}});
})();
